### ISSUE TITLE
github.com/esimov/caire/cmd/caire missing

### ISSUE THREAD

**Issue by Sugarbank** [esimov/caire#16]
hi link github.com/esimov/caire/cmd/caire is down?

**Comment by jmank88** [comment]
Though you 'go get' that package/path, the url is more complicated since it is not a top level repo: https://github.com/esimov/caire/tree/master/cmd/caire

**Comment by Scott-MacD** [comment]
Also might be worth noting for anyone else who might stumble upon this issue, if you've just installed go to try this out, make sure you start a new terminal session after updating your PATHS variable before running "go get". Even though all the go tools themselves were up and running, "go get" gave me a similar error because it wasn't able to locate the submodules in the working directory.

**Comment by esimov** [comment]
@Sugarbank I think in your case it's applicable what @Scott-MacD is telling. Normally you get the package with link you have just tried, but please make sure all the `PATH` and `GOPATH` variables are set correctly.
