### ISSUE TITLE
Resize not working properly when both height and width are passed in percentages

### ISSUE THREAD

**Issue by kartikwar** [esimov/caire#85]
It seems the resize is not working properly when both height and width are passed in percentages

Request:-
go run github.com/esimov/caire/cmd/caire@latest  -in /home/kartik/example.jpg -out output.jpg  -perc=1 -width=50 -height=50

![example](https://user-images.githubusercontent.com/17046431/195260322-3287ed15-d150-48b0-a327-22b0a18c6524.jpg)

![output](https://user-images.githubusercontent.com/17046431/195260296-09d4debe-2ad7-4d4f-9c44-3e7de8eb179c.jpg)

The output just seems to be scaled down

**Comment by esimov** [comment]
No, this has nothing related to the fact that the resize dimensions are passed in percentage. This is how the algorithm is supposed to work. Let me explain why. Each time before the seam removal algorithm is invoked first it's analyzed if an image rescale operation could be performed to obtain the new image closest to the desired size. What this means? Well in other words first the image is scaled down or up by preserving the image aspect ratio, then the seam carving algorithm is applied only to the remaining pixels. This because the seam carving operation is a quite costly process, so this way we can speedup considerably the execution time. To translate what I'm trying to explain to your use case: the input image size is 670x447. 50% rescale results in 334.5x223. This rounded down will be 334x223, so the seam carving algorithm will be invoked only for the remaining one pixel column. Hope that's clear now.

**Comment by kartikwar** [comment]
thanks for the explanation. yes its clear now
