### ISSUE TITLE
Algorithm takes forever to run for this image

### ISSUE THREAD

**Issue by kartikwar** [esimov/caire#87]
I tried using the algorithm on a solid color image (less number of colors) and it took 6 minutes and 40 seconds to compute the result. Can you please check why it takes so long for this computation?

Command:- 
**go run main.go  -in input/168.jpg --perc=1 -out output.jpg    -height=20  -mask saliency/168.png**  

Input:-
![168](https://user-images.githubusercontent.com/17046431/196126141-70a27e04-d054-4b2c-a716-2524c6ed0504.jpg)

Mask:-
![168](https://user-images.githubusercontent.com/17046431/196126276-ee3053e7-d7ce-4101-8224-213e7d837cf0.png)

**Comment by esimov** [comment]
The image color composition has nothing to do with the time required for the process completion. The reason is the image size: it has a resolution of 2048x1708. Now, because you are resizing only vertically the image rescaling process is not involved prior invoking the seam carving operation, so it's quite expected to take more time to complete.
